# Generated by Django 4.1.7 on 2023-04-05 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_carts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carts',
        ),
    ]
